### ISSUE TITLE
QoL Change: Linking to an expanded workshop archive

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/hack.uclaacm.com#167]
Hello hello! Always a huge fan of the Hack website, and in particular, I wanted to share with my devs some of the previous resources y'all have made. This is a very small QoL change, but is it possible to link to the `/archive/` page with a category already expanded?

I'm imagining: I link `https://hack.uclaacm.com/archive?2019-hackschool` or `https://hack.uclaacm.com/archive/#2019-hackschool`

And the user loads in to:

![Screen Shot 2021-02-18 at 7 54 18 PM](https://user-images.githubusercontent.com/14893287/108455422-1b289b80-7223-11eb-9ee0-5eae5e41749f.png)

Normally, I just tell them to scroll down to a header and click to expand (which is totally fine), but I think this might be a cool addition! Any thoughts? Not sure how this plays into Gatsby's router!

p.s. still sharing Hackschool and JS Chats content 😊

**Comment by TimothyGu** [comment]
We should be able to use a two-pronged fix:

1. Add `id="some_id"` to each of the drop downs. This makes the browser automatically scroll to the section when a URL with the hash is visied.

2. When the dropdown is expanded, run:
   ```js
   if (typeof history !== 'undefined') {
     history.pushState(state, title, `#${idOfCurrentSection}`);
   }
   ```
   This updates the current URL to include the `#` so that people can copy it. See https://developer.mozilla.org/en-US/docs/Web/API/History/pushState for more information about the API. We also include an `if`-condition to allow this code to work even when rendering on the server.

**Comment by jodymlin** [comment]
Ooh yes this is a very good idea 😃 We are in the process of restructuring our Workshop Archive code, so when that's mostly complete we can work on getting this added!

**Comment by EinarBalan** [comment]
change of plans bc dumb: copy link button w icon

**Comment by khxia** [comment]
@katelynsyu 

- automatic dropdown and scrolldown based on slug
- have a copy button that lets you copy the current slug to the clipboard
